### ISSUE TITLE
[sdk] Checklist for mainnet

### ISSUE THREAD

**Issue by limbofeather** [zestyxyz/zesty-ads-sdk-web#33]
- [x] replace Rinkeby Graph endpoints with mainnet
- [x] replace default ad with Zesty
- [x] URL should direct to ad space
- [x] Docs for integrating A-Frame, OBS, R3F, Three.JS
